theme: jekyll-theme-minimal
title: neuroady's homepage
description: My personal website which will be used as a placeholder for my public interests.

remote_theme: pages-themes/minimal@v0.2.0

google_analytics: G-3GKSCZBXXE

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
